In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [2]:
metro_NY_file = 'Police Dataset/Large_metro_areas/NYPD_Arrests_Data__Historic_.csv'
metro_NY_df = pd.read_csv(metro_NY_file)
metro_NY_df.head()

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lon_Lat
0,190294601,11/23/2018,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200512,F,B,40,0.0,25-44,M,BLACK,1008096.0,233595.0,40.807816,-73.913863,POINT (-73.91386266099995 40.807816227000046)
1,190266280,11/21/2018,665.0,NaN,NaN,NaN,PL 4902001,F,Q,109,0.0,25-44,M,BLACK HISPANIC,1032084.0,216954.0,40.762044,-73.827330,POINT (-73.82732958099997 40.762043893000055)
2,190159521,11/19/2018,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200000,M,K,77,0.0,25-44,M,BLACK,1003508.0,185056.0,40.674600,-73.930575,POINT (-73.93057482199998 40.67459999000005)
3,190080571,11/16/2018,475.0,NaN,NaN,NaN,PL 1651601,M,Q,103,1.0,18-24,M,BLACK,1039726.0,195270.0,40.702482,-73.799922,POINT (-73.799922252 40.702482133000046)
4,190027735,11/15/2018,475.0,NaN,NaN,NaN,PL 1651601,M,M,10,1.0,45-64,M,WHITE HISPANIC,984669.0,210807.0,40.745301,-73.998489,POINT (-73.99848931699995 40.745301320000074)

In [3]:
#Cleaning by filling nan with zero

metro_NY_df.fillna(0)

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lon_Lat
0,190294601,11/23/2018,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200512,F,B,40,0.0,25-44,M,BLACK,1008096.0,233595.0,40.807816,-73.913863,POINT (-73.91386266099995 40.807816227000046)
1,190266280,11/21/2018,665.0,0,0.0,0,PL 4902001,F,Q,109,0.0,25-44,M,BLACK HISPANIC,1032084.0,216954.0,40.762044,-73.827330,POINT (-73.82732958099997 40.762043893000055)
2,190159521,11/19/2018,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200000,M,K,77,0.0,25-44,M,BLACK,1003508.0,185056.0,40.674600,-73.930575,POINT (-73.93057482199998 40.67459999000005)
3,190080571,11/16/2018,475.0,0,0.0,0,PL 1651601,M,Q,103,1.0,18-24,M,BLACK,1039726.0,195270.0,40.702482,-73.799922,POINT (-73.799922252 40.702482133000046)
4,190027735,11/15/2018,475.0,0,0.0,0,PL 1651601,M,M,10,1.0,45-64,M,WHITE HISPANIC,984669.0,210807.0,40.745301,-73.998489,POINT (-73.99848931699995 40.745301320000074)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5012951,10046926,01/11/2006,969.0,"TRAFFIC,UNCLASSIFIED INFRACTION",881.0,OTHER TRAFFIC INFRACTION,VTL051101A,M,Q,104,0.0,18-24,M,WHITE HISPANIC,1011351.0,198969.0,40.712767,-73.902244,POINT (-73.90224422999995 40.71276740300004)
5012952,9961305,01/05/2006,478.0,"THEFT OF SERVICES, UNCLASSIFIED",343.0,OTHER OFFENSES RELATED TO THEFT,PL 1651503,M,M,25,1.0,45-64,M,BLACK,1002776.0,231994.0,40.803435,-73.933084,POINT (-73.93308447999993 40.80343468000007)
5012953,9960771,01/05/2006,730.0,MANUFACTURE UNAUTHORIZED RECORDINGS,126.0,MISCELLANEOUS PENAL LAW,PL 2754000,F,K,88,0.0,45-64,M,BLACK,991573.0,191853.0,40.693274,-73.973594,POINT (-73.97359405499998 40.69327412300004)
5012954,10040354,01/10/2006,969.0,"TRAFFIC,UNCLASSIFIED INFRACTION",881.0,OTHER TRAFFIC INFRACTION,VTL051101A,M,Q,108,0.0,25-44,M,WHITE,1006264.0,210118.0,40.743383,-73.920557,POINT (-73.92055729099997 40.743382801000045)
5012955,10003945,01/06/2006,521.0,"CONTROLLED SUBSTANCE, SALE 5",117.0,DANGEROUS DRUGS,PL 2203100,F,K,61,0.0,25-44,M,WHITE HISPANIC,998319.0,153692.0,40.588522,-73.949347,POINT (-73.94934695399996 40.58852221700005)

In [4]:
deaths_arrests_file = 'Police Dataset/deaths_arrests_race.csv'
deaths_arrests_df = pd.read_csv(deaths_arrests_file)
deaths_arrests_df.head()

,State,City,PD,Black People Killed by Police (1/1/2013-12/31/2019),Hispanic People Killed by Police (1/1/2013-12/31/2019),Native American People Killed by Police (1/1/2013-12/31/2019),Asian People Killed by Police (1/1/2013-12/31/2019),Pacific Islanders Killed by Police (1/1/2013-12/31/2019),White People Killed by Police (1/1/2013-12/31/2019),Unknown Race People Killed by Police (1/1/2013-12/31/2019),...,Violent crimes 2015 (if reported by agency),Violent crimes 2016 (if reported by agency),Violent crimes 2017 (if reported by agency),Violent crimes 2018 (if reported by agency),2013 Total Arrests (UCR Data),2014 Total Arrests,2015 Total Arrests,2016 Total Arrests,2017 Total Arrests,2018 Total Arrests
0,New Mexico,Albuquerque,Albuquerque Police Department,3.0,18.0,NaN,NaN,NaN,10.0,1.0,...,5406.0,6245.0,7686.0,7646.0,27700.0,25447.0,22126.0,20341.0,21130.0,22254.0
1,California,Anaheim,Anaheim Police Department,3.0,7.0,NaN,NaN,NaN,3.0,NaN,...,1271.0,1209.0,1253.0,1192.0,7891.0,8137.0,8381.0,9415.0,8869.0,10019.0
2,Alaska,Anchorage,Anchorage Police Department,1.0,1.0,2.0,NaN,NaN,5.0,4.0,...,3226.0,3422.0,3564.0,3824.0,17601.0,14748.0,14387.0,13294.0,13871.0,13973.0
3,Texas,Arlington,Arlington Police Department,7.0,1.0,NaN,1.0,NaN,4.0,1.0,...,1946.0,2188.0,NaN,1784.0,17258.0,16222.0,13989.0,11024.0,8397.0,9566.0
4,Georgia,Atlanta,Atlanta Police Department,13.0,NaN,NaN,NaN,NaN,1.0,1.0,...,5203.0,5121.0,4504.0,3814.0,30505.0,26958.0,NaN,22161.0,22581.0,NaN

In [5]:
#Cleaning data by zero fill NAN to get a number to count death per arrest

deaths_arrests_df.fillna(0)

,State,City,PD,Black People Killed by Police (1/1/2013-12/31/2019),Hispanic People Killed by Police (1/1/2013-12/31/2019),Native American People Killed by Police (1/1/2013-12/31/2019),Asian People Killed by Police (1/1/2013-12/31/2019),Pacific Islanders Killed by Police (1/1/2013-12/31/2019),White People Killed by Police (1/1/2013-12/31/2019),Unknown Race People Killed by Police (1/1/2013-12/31/2019),...,Violent crimes 2015 (if reported by agency),Violent crimes 2016 (if reported by agency),Violent crimes 2017 (if reported by agency),Violent crimes 2018 (if reported by agency),2013 Total Arrests (UCR Data),2014 Total Arrests,2015 Total Arrests,2016 Total Arrests,2017 Total Arrests,2018 Total Arrests
0,New Mexico,Albuquerque,Albuquerque Police Department,3.0,18.0,0.0,0.0,0.0,10.0,1.0,...,5406.0,6245.0,7686.0,7646.0,27700.0,25447.0,22126.0,20341.0,21130.0,22254.0
1,California,Anaheim,Anaheim Police Department,3.0,7.0,0.0,0.0,0.0,3.0,0.0,...,1271.0,1209.0,1253.0,1192.0,7891.0,8137.0,8381.0,9415.0,8869.0,10019.0
2,Alaska,Anchorage,Anchorage Police Department,1.0,1.0,2.0,0.0,0.0,5.0,4.0,...,3226.0,3422.0,3564.0,3824.0,17601.0,14748.0,14387.0,13294.0,13871.0,13973.0
3,Texas,Arlington,Arlington Police Department,7.0,1.0,0.0,1.0,0.0,4.0,1.0,...,1946.0,2188.0,0.0,1784.0,17258.0,16222.0,13989.0,11024.0,8397.0,9566.0
4,Georgia,Atlanta,Atlanta Police Department,13.0,0.0,0.0,0.0,0.0,1.0,1.0,...,5203.0,5121.0,4504.0,3814.0,30505.0,26958.0,0.0,22161.0,22581.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Arizona,Tucson,Tucson Police Department,2.0,10.0,0.0,0.0,0.0,10.0,6.0,...,3472.0,4245.0,4268.0,3958.0,31892.0,32313.0,32294.0,33442.0,30569.0,28858.0
96,Oklahoma,Tulsa,Tulsa Police Department,7.0,4.0,0.0,1.0,0.0,14.0,1.0,...,3628.0,4444.0,4214.0,4294.0,16360.0,14739.0,15769.0,14311.0,12666.0,13303.0
97,Virginia,Virginia Beach,Virginia Beach Police Department,3.0,0.0,0.0,0.0,0.0,2.0,1.0,...,626.0,700.0,625.0,528.0,24359.0,23247.0,20259.0,19190.0,18668.0,17071.0
98,Kansas,Wichita,Wichita Police Department,1.0,2.0,0.0,0.0,0.0,10.0,0.0,...,3839.0,4136.0,3998.0,4622.0,10566.0,9323.0,9307.0,9120.0,8322.0,3931.0
99,North Carolina,Winston-Salem,Winston-Salem Police Department,3.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,19742.0,18875.0,16146.0,15432.0,0.0,12786.0

In [6]:
fatal_encouters_file = 'Police Dataset/fatal_encounters_dot_org.csv'
fatal_encouters_df = pd.read_csv(fatal_encouters_file, index_col=0)
fatal_encouters_df.head()

,Subject's name,Subject's age,Subject's gender,Subject's race,Subject's race with imputations,Imputation probability,URL of image of deceased,Date of injury resulting in death (month/day/year),Location of injury (address),Location of death (city),...,Cause of death,A brief description of the circumstances surrounding the death,"Dispositions/Exclusions INTERNAL USE, NOT FOR ANALYSIS",Link to news article or photo of official document,"Symptoms of mental illness? INTERNAL USE, NOT FOR ANALYSIS",Video,Date&Description,Unique ID formula,Unique identifier (redundant),Date (Year)
Unique ID,,,,,,,,,,,,,,,,,,,,,
25747,Mark A. Horton,21,Male,African-American/Black,African-American/Black,not imputed,NaN,01/01/2000,Davison Freeway,Detroit,...,Vehicle,Two Detroit men killed when their car crashed ...,Unreported,https://drive.google.com/file/d/1-nK-RohgiM-tZ...,No,NaN,1/1/2000: Two Detroit men killed when their ca...,NaN,25747,2000
25748,Phillip A. Blurbridge,19,Male,African-American/Black,African-American/Black,not imputed,NaN,01/01/2000,Davison Freeway,Detroit,...,Vehicle,Two Detroit men killed when their car crashed ...,Unreported,https://drive.google.com/file/d/1-nK-RohgiM-tZ...,No,NaN,1/1/2000: Two Detroit men killed when their ca...,NaN,25748,2000
25746,Samuel H. Knapp,17,Male,European-American/White,European-American/White,not imputed,NaN,01/01/2000,27898-27804 US-101,Willits,...,Vehicle,Samuel Knapp was allegedly driving a stolen ve...,Unreported,https://drive.google.com/file/d/10DisrV8K5ReP1...,No,NaN,1/1/2000: Samuel Knapp was allegedly driving a...,NaN,25746,2000
25749,Mark Ortiz,23,Male,Hispanic/Latino,Hispanic/Latino,not imputed,NaN,01/01/2000,600 W Cherry Ln,Carlsbad,...,Vehicle,A motorcycle was allegedly being driven errati...,Unreported,https://drive.google.com/file/d/1qAEefRjX_aTtC...,No,NaN,1/1/2000: A motorcycle was allegedly being dri...,NaN,25749,2000
1,LaTanya Janelle McCoy,24,Female,African-American/Black,African-American/Black,not imputed,NaN,01/02/2000,5700 block Mack Road,Sacramento,...,Vehicle,LaTanya Janelle McCoy's car was struck from be...,Unknown,http://www.recordnet.com/article/20000110/A_NE...,No,NaN,1/2/2000: LaTanya Janelle McCoy's car was stru...,NaN,1,2000

In [7]:

# Cleaning data by dropping columns with incomplete data sets and no added value

Cleanfatal_encouters_df= fatal_encouters_df[["Subject's name", "Subject's age", "Subject's gender", "Subject's race",
                                                    "Cause of death", "Symptoms of mental illness? INTERNAL USE, NOT FOR ANALYSIS", "Date of injury resulting in death (month/day/year)","Date (Year)"]]
Cleanfatal_encouters_df

,Subject's name,Subject's age,Subject's gender,Subject's race,Cause of death,"Symptoms of mental illness? INTERNAL USE, NOT FOR ANALYSIS",Date of injury resulting in death (month/day/year),Date (Year)
Unique ID,,,,,,,,
25747,Mark A. Horton,21,Male,African-American/Black,Vehicle,No,01/01/2000,2000
25748,Phillip A. Blurbridge,19,Male,African-American/Black,Vehicle,No,01/01/2000,2000
25746,Samuel H. Knapp,17,Male,European-American/White,Vehicle,No,01/01/2000,2000
25749,Mark Ortiz,23,Male,Hispanic/Latino,Vehicle,No,01/01/2000,2000
1,LaTanya Janelle McCoy,24,Female,African-American/Black,Vehicle,No,01/02/2000,2000
...,...,...,...,...,...,...,...,...
28190,Mary Lawrence,39,Female,Race unspecified,Gunshot,No,06/03/2020,2020
28191,Guadalupe Francisco-Martinez,37,Female,Hispanic/Latino,Vehicle,No,06/03/2020,2020
28193,Scott Hutton,36,Male,European-American/White,Gunshot,No,06/03/2020,2020
28194,Eric Anthony Galvan,25,Male,Hispanic/Latino,Gunshot,No,06/03/2020,2020
28195,Juan Carlos Lopez,NaN,Male,Hispanic/Latino,Gunshot,No,06/04/2020,2020

In [8]:
fatal_shootings_file = 'Police Dataset/fatal-police-shootings-data.csv'
fatal_shootings_df = pd.read_csv(fatal_shootings_file)
fatal_shootings_df

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera
0,3,Tim Elliot,2015-01-02,shot,gun,53.0,M,A,Shelton,WA,True,attack,Not fleeing,False
1,4,Lewis Lee Lembke,2015-01-02,shot,gun,47.0,M,W,Aloha,OR,False,attack,Not fleeing,False
2,5,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23.0,M,H,Wichita,KS,False,other,Not fleeing,False
3,8,Matthew Hoffman,2015-01-04,shot,toy weapon,32.0,M,W,San Francisco,CA,True,attack,Not fleeing,False
4,9,Michael Rodriguez,2015-01-04,shot,nail gun,39.0,M,H,Evans,CO,False,attack,Not fleeing,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5411,5921,William Slyter,2020-06-13,shot,gun,22.0,M,W,Kansas City,MO,False,other,Other,False
5412,5922,TK TK,2020-06-13,shot,undetermined,NaN,M,NaN,San Bernardino,CA,False,attack,Not fleeing,False
5413,5924,Nicholas Hirsh,2020-06-15,shot,gun,31.0,M,W,Lawrence,KS,False,attack,Car,False
5414,5926,TK TK,2020-06-16,shot,gun,24.0,M,NaN,Beach Park,IL,False,attack,Not fleeing,False
5415,5927,TK TK,2020-06-16,shot,gun,27.0,M,NaN,Phoenix,AZ,False,attack,Not fleeing,False

In [9]:
killings_file = 'Police Dataset/police_killings.csv'
killings_df = pd.read_csv(killings_file, index_col=0)
killings_df

,Victim's age,Victim's gender,Victim's race,URL of image of victim,Date of Incident (month/day/year),Street Address of Incident,City,State,Zipcode,County,...,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65
Victim's name,,,,,,,,,,,,,,,,,,,,,
Eric M. Tellez,28,Male,White,https://fatalencounters.org/wp-content/uploads...,31/12/2019,Broad St.,Globe,AZ,85501.0,Gila,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Name withheld by police,NaN,Male,Unknown race,NaN,31/12/2019,7239-7411 I-40,Memphis,AR,38103.0,Crittenden,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Terry Hudson,57,Male,Black,NaN,31/12/2019,3600 N 24th St,Omaha,NE,68110.0,Douglas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Malik Williams,23,Male,Black,NaN,31/12/2019,30800 14th Avenue South,Federal Way,WA,98003.0,King,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Frederick Perkins,37,Male,Black,NaN,31/12/2019,17057 N Outer 40 Rd,Chesterfield,MO,63005.0,St. Louis,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
#cleaning data/Dropping columns with incomplete data sets
Cleankillings_df= killings_df[["Victim's age", "Victim's gender", "Victim's race", "Date of Incident (month/day/year)",
                                                 "City", "State", "Zipcode"]]
Cleankillings_df.head(35)

,Victim's age,Victim's gender,Victim's race,Date of Incident (month/day/year),City,State,Zipcode
Victim's name,,,,,,,
Eric M. Tellez,28,Male,White,31/12/2019,Globe,AZ,85501.0
Name withheld by police,NaN,Male,Unknown race,31/12/2019,Memphis,AR,38103.0
Terry Hudson,57,Male,Black,31/12/2019,Omaha,NE,68110.0
Malik Williams,23,Male,Black,31/12/2019,Federal Way,WA,98003.0
Frederick Perkins,37,Male,Black,31/12/2019,Chesterfield,MO,63005.0
Michael Vincent Davis,49,Male,White,31/12/2019,Cross Lanes,WV,25313.0
Brian Elkins,47,Male,Unknown race,31/12/2019,Blue Mountain,MS,38610.0
Debra D. Arbuckle,51,Female,White,30/12/2019,Wichita,KS,67207.0
Name withheld by police,NaN,Male,Unknown race,30/12/2019,Houston,TX,77033.0
Cody McCaulou,27,Male,White,30/12/2019,Fulton,MO,65251.0
Manuel Gonzales Verdugo,50,Male,Hispanic,29/12/2019,El Centro,CA,92243.0
John Bott,76,Male,Unknown race,29/12/2019,Byhalia,MS,38611.0
Patrick Alden,29,Male,Unknown race,29/12/2019,Rapid City,SD,57701.0
Name withheld by police,NaN,NaN,Unknown race,29/12/2019,Lafayette,IN,47905.0
Kelly Michael Stephens,34,Male,Unknown race,29/12/2019,Juneau,AK,99801.0
Troy Kirk,31,Male,Unknown race,28/12/2019,Lancaster,OH,43130.0
A.B. Carr,31,Male,White,28/12/2019,Elizabethton,TN,37643.0
Albert Benjamin Simon,52,Male,White,28/12/2019,Houston,TX,77030.0
Craig Ellis See,34,Male,White,28/12/2019,Clearlake Oaks,CA,95423.0
Heriberto Rodriguez,27,Male,Unknown race,28/12/2019,Bakersfield,CA,93305.0
John Lowell Dollen,NaN,Male,Unknown race,27/12/2019,Linthicum Heights,MD,21090.0
Henry Kistler Berry III,43,Male,White,27/12/2019,Newport News,VA,23606.0
Frederick Jeremy Atkin,42,Male,White,27/12/2019,South Ogden,UT,84405.0
Christopher Camacho,16,Male,Unknown race,27/12/2019,Limerick,ME,4048.0
Antonio Smith,35,Male,Black,26/12/2019,Memphis,TN,38127.0
Juan Rosa,35,Male,Hispanic,26/12/2019,Auburndale,FL,33823.0
Deangelo Rashad Martin,23,Male,Black,25/12/2019,Atlanta,GA,30349.0
Lori Jean Canada,59,Female,Unknown race,25/12/2019,Ocala,FL,34476.0
David A. White,56,Male,Unknown race,24/12/2019,Springfield,MO,65807.0
Harvey Cantrell,65,Male,Unknown race,24/12/2019,Deltona,FL,32725.0
Elray Barber,60,Male,Black,24/12/2019,Oklahoma City,OK,73111.0
Richard Ruiz,38,Male,Unknown race,23/12/2019,Phoenix,AZ,85033.0
Austin Chase Swindle,24,Male,White,23/12/2019,Bryant,AR,72022.0
Macario Hernandez,34,Male,Hispanic,23/12/2019,San Antonio,TX,78204.0
Romir Talley,24,Male,Black,22/12/2019,Pittsburgh,PA,15221.0

In [11]:
#Additional cleaning of data by dropping nan
newCleankillings_df_df= killings_df[["Victim's age", "Victim's gender", "Victim's race", "Date of Incident (month/day/year)",
                                                 "City", "State", "Zipcode"]]
newCleankillings_df=Cleankillings_df.dropna()
newCleankillings_df

,Victim's age,Victim's gender,Victim's race,Date of Incident (month/day/year),City,State,Zipcode
Victim's name,,,,,,,
Eric M. Tellez,28,Male,White,31/12/2019,Globe,AZ,85501.0
Terry Hudson,57,Male,Black,31/12/2019,Omaha,NE,68110.0
Malik Williams,23,Male,Black,31/12/2019,Federal Way,WA,98003.0
Frederick Perkins,37,Male,Black,31/12/2019,Chesterfield,MO,63005.0
Michael Vincent Davis,49,Male,White,31/12/2019,Cross Lanes,WV,25313.0
...,...,...,...,...,...,...,...
Mark Chavez,49,Male,Hispanic,01/01/2013,Farmington,NM,87401.0
Tyree Bell,31,Male,Black,01/01/2013,Omaha,NE,68111.0
Christopher Tavares,21,Male,Hispanic,01/01/2013,Pueblo,CO,81008.0
Andrew L. Closson,21,Male,White,01/01/2013,Gordon,WI,54838.0
Andrew Layton,26,Male,White,01/01/2013,Mankato,MN,56001.0

In [12]:
politics_file = 'Police Dataset/politics_538.csv'
politics_df = pd.read_csv(politics_file)
politics_df

,Area,Republican Vote Share,Partisan Segregation
0,"Jackson, Mississippi",0.399,0.63
1,New Orleans,0.416,0.58
2,"Baton Rouge, Louisiana",0.497,0.56
3,"Birmingham, Alabama",0.455,0.56
4,"Shreveport, Louisiana",0.444,0.56
...,...,...,...
148,"Palm Bay-Melbourne, Florida",0.587,0.12
149,"Greater Myrtle Beach area, South Carolina and ...",0.692,0.12
150,City of Honolulu,0.330,0.12
151,"Bonita Springs, Florida",0.638,0.12
152,"Murrieta-Temecula-Menifee, California",0.598,0.10

In [13]:
wash_post_shootings_file = 'Police Dataset/shootings_wash_post.csv'
wash_post_shootings_df = pd.read_csv(wash_post_shootings_file)
wash_post_shootings_df

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera
0,3,Tim Elliot,2015-01-02,shot,gun,53.0,M,A,Shelton,WA,True,attack,Not fleeing,False
1,4,Lewis Lee Lembke,2015-01-02,shot,gun,47.0,M,W,Aloha,OR,False,attack,Not fleeing,False
2,5,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23.0,M,H,Wichita,KS,False,other,Not fleeing,False
3,8,Matthew Hoffman,2015-01-04,shot,toy weapon,32.0,M,W,San Francisco,CA,True,attack,Not fleeing,False
4,9,Michael Rodriguez,2015-01-04,shot,nail gun,39.0,M,H,Evans,CO,False,attack,Not fleeing,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5384,5878,TK TK,2020-05-31,shot and Tasered,gun,NaN,M,W,Watertown,WI,False,attack,Not fleeing,False
5385,5842,David McAtee,2020-06-01,shot,gun,53.0,M,B,Louisville,KY,False,attack,NaN,True
5386,5866,Jorge Gomez,2020-06-01,shot,gun,25.0,M,H,Las Vegas,NV,False,attack,Not fleeing,False
5387,5867,Ryan Emblem Moore,2020-06-01,shot,NaN,36.0,M,W,Fayetteville,AR,False,undetermined,Not fleeing,False
5388,5869,Robert James Lyon,2020-06-02,shot,gun,65.0,M,NaN,Cottonwood,CA,False,other,Not fleeing,False